config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  resources :games do
    resources :involved_companies, only: %i[create destroy]

    post "add_genre", on: :member
    delete "remove_genre", on: :member

    post "add_platform", on: :member
    delete "remove_platform", on: :member

    resources :critics, only: %i[create]
  end
  resources :companies do
    resources :critics, only: %i[create]
  end

  resources :critics, only: :destroy
end

app/models/critic.rb
class Critic < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :criticable, polymorphic: true, counter_cache: true

  validates :title, presence: true
  validates :body, length: { in: 10..100 }
end

app/controllers/critics_controller.rb
class CriticsController < ApplicationController
  # POST game/:game_id/critic
  # POST company/:company_id/critic
  def create
    @involved_company_dev = InvolvedCompany.new
    @involved_company_pub = InvolvedCompany.new

    if params[:game_id]
      @criticable = Game.find(params[:game_id])
      @game = Game.find(params[:game_id])
    elsif params[:company_id]
      @criticable = Company.find(params[:company_id])
      @company = Company.find(params[:company_id])
    end

    @critic = @criticable.critics.new(critic_params)

    if @critic.save
      redirect_to @criticable, notice: "Critic was successfully created."
    elsif params[:game_id]
      render "games/show", status: :unprocessable_entity
    elsif params[:company_id]
      render "companies/show", status: :unprocessable_entity
    end
  end

  def destroy
    @critic = Critic.find(params[:id])
    redirect_to @critic.criticable,  notice: "Critic was successfully destroyed."
  end

  private

  def critic_params
    params.require(:critic).permit(:title, :body, :user_id)
  end
end

app/helpers/critics_helper.rb
module CriticsHelper
end

app/views/critics/_critic.html.erb
<div class="critic_card">
  <h4>
    <%= critic.title %>
  </h4>
  <p><span>by <%= critic.user.username %></span></p>
  <p><%= critic.body %></p>
  <div clas="critic_card-footer">
    <p><span>Send <%= critic.created_at %></span></p>
    <%= button_to "Approve" %>
    <%= button_to "Delete", critic_path(critic), method: :delete %>
  </div>
</div>

app/views/critics/_form.html.erb
<div class="form_critic">
  <%= form_with model: [criticable, critic] do |f| %>
    <% if critic.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(critic.errors.count, "error") %> prohibited this critic from being saved:</h2>

        <ul>
          <% critic.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_field :user_id %>
    <%= f.text_field :title, placeholder: "Critic title", style: "display: block" %>
    <%= f.text_area :body, placeholder: "Critic body ...", style: "display: block"%>
    <%= f.submit "Create Critic"%>
  <% end %>
</div>