config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  resources :games do
    resources :involved_companies, only: %i[create destroy]

    post "add_genre", on: :member
    delete "remove_genre", on: :member

    post "add_platform", on: :member
    delete "remove_platform", on: :member

    resources :critics, only: %i[create]
  end
  resources :companies do
    resources :critics, only: %i[create]
  end

  resources :critics, only: :destroy
end

app/models/game.rb
class Game < ApplicationRecord
  # Associations
  belongs_to :parent, class_name: "Game",
                      optional: true
  has_many :expansions, class_name: "Game",
                        foreign_key: "parent_id",
                        dependent: :nullify,
                        inverse_of: "parent"

  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies

  has_and_belongs_to_many :genres
  has_and_belongs_to_many :platforms

  has_many :critics, as: :criticable, dependent: :destroy

  has_one_attached :cover

  # Validations
  validates :name, presence: true
  validates :summary, length: { in: 10..1000 }, allow_nil: true
  validates :release_date, comparison: { less_than: Time.zone.now }, allow_nil: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 },
                     allow_nil: true
  validates :parent, inclusion: { in: proc { Game.main_game } },
                     unless: proc { main_game? || category.nil? }
  validates :parent, absence: true, if: proc { main_game? }

  enum category: { main_game: 0, expansion: 1 }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy add_genre remove_genre add_platform remove_platform]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
    @involved_company_dev = InvolvedCompany.new
    @involved_company_pub = InvolvedCompany.new
    @critic = Critic.new
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to games_path, notice: "Game was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to games_path, notice: "Game was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: "Game was successfully destroyed."
  end

  def add_genre
    @genre = Genre.find(params[:genre_id])
    @game.genres << @genre
    redirect_to @game
  end

  def remove_genre
    @genre = Genre.find(params[:genre_id])
    @game.genres.delete(@genre)
    redirect_to @game
  end

  def add_platform
    @platform = Platform.find(params[:platform_id])
    @game.platforms << @platform
    redirect_to @game
  end

  def remove_platform
    @platform = Platform.find(params[:platform_id])
    @game.platforms.delete(@platform)
    redirect_to @game
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id, :cover)
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def self.format_categories(categories)
    categories.map do |cat|
      [cat.split("_").map(&:capitalize).join(" "), cat]
    end
  end

  def self.filter_involved_companies(involved_companies, option)
    option == "developer" ? involved_companies.select(&:developer?) : involved_companies.select(&:publisher?)
  end
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_area :summary %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.date_field :release_date %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, GamesHelper.format_categories(Game.categories.keys), 
                               include_blank: "--Select Category" %>
  </div>

  <div>
    <%= form.label :parent_id, "Parent Game" , style: "display: block" %>
    <%= form.collection_select :parent_id, Game.main_game, 
                                           :id, 
                                           :name, 
                                           include_blank: "-- No parent" %>
  </div>

  <div>
    <% if game.cover.attached? %>
      <%= image_tag game.cover %>
    <% end %>
    <%= form.label :cover, style: "display: block" %>
    <%= form.file_field :cover %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <% if game.cover.attached? %>
    <%= image_tag game.cover, alt: "game_cover" %>
  <% end %>
  <h1>
    <%= game.name %>
  </h1>
  <p>
    <% if game.release_date %>
      <span><%= game.release_date.year %></span>
    <% end %>
  </p>

  <p>
    <%= game.rating %>
  </p>

  <div class="details_section">
    <h3>Game Details</h3>
    <p>
      <%= game.summary %>
    </p>

    <h4>Genres</h4>
    <div>
      <ul>
        <% game.genres.each do |genre| %>
          <li>
            <%= genre.name %>
            <%= form_with url: remove_genre_game_path(game), method: :delete do |f|%>
              <%= f.hidden_field :genre_id, value: genre.id %>
              <%= f.submit "Delete" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <h4>Platforms</h4>
      <ul>
        <% game.platforms.each do |platform| %>
          <li>
            <%= platform.name %>
            <%= form_with url: remove_platform_game_path(game), method: :delete do |f|%>
              <%= f.hidden_field :platform_id, value: platform.id %>
              <%= f.submit "Delete" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    <h4>Developers</h4>
    <div>
      <ul>
        <% GamesHelper.filter_involved_companies(game.involved_companies, "developer").each do |invol_dev| %>
          <li>
            <%= form_with model: [game, invol_dev], method: :delete do |f| %>
              <%= f.text_field :company_id, hidden: true %>
              <%= f.text_field :developer, value: true, hidden: true %>
              <%= f.submit "Delete" %> 
            <% end %>
            <%= invol_dev.company.name %>
          </li>
        <% end %>
      </ul>
    </div>
    <h4>Publishers</h4>
    <div>
      <ul>
        <% GamesHelper.filter_involved_companies(game.involved_companies, "publisher").each do |invol_pub| %>
          <li>
            <%= form_with model: [game, invol_pub], method: :delete do |f| %>
              <%= f.text_field :company_id, hidden: true %>
              <%= f.text_field :publisher, value: true, hidden: true %>
              <%= f.submit "Delete" %> 
            <% end %>
            <%= invol_pub.company.name %>
          </li>
        <% end %>
      </ul>
    </div>

    <h2>Add relations</h2>
    <div>
      <%= form_with url: add_genre_game_path(game) do |f|%>
        <%= f.collection_select :genre_id, (Genre.all - game.genres), :id, :name, include_blank: "Select genre"  %>
        <%= f.submit "Add genre" %>
      <% end %>
    </div>
    <div>
      <%= form_with url: add_platform_game_path(game) do |f| %>
        <%= f.collection_select :platform_id, (Platform.all - game.platforms),
                                            :id,
                                            :name,
                                            include_blank: "Select platform" %>
        <%= f.submit "Add platform" %>
      <% end %>
    </div>
    <div>
      <%= form_with model: [game, involved_company_dev] do |f| %>
        <% if involved_company_dev.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(involved_company_dev.errors.count, "error") %> prohibited this involved company from being saved:</h2>
            <ul>
              <% involved_company_dev.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.text_field :developer, value: true, hidden: true %>
        <%= f.collection_select :company_id, Company.all, 
                                            :id, 
                                            :name, 
                                            include_blank: "Select Company" %>
        <%= f.submit "Add developer" %>
      <% end %>
    </div>
    <div>
      <%= form_with model: [game, involved_company_pub] do |f| %>
        <% if involved_company_pub.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(involved_company_pub.errors.count, "error") %> prohibited this involved company from being saved:</h2>
            <ul>
              <% involved_company_pub.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.text_field :publisher, value: true, hidden: true %>
        <%= f.collection_select :company_id, Company.all, 
                                            :id, 
                                            :name, 
                                            include_blank: "Select Company" %>
        <%= f.submit "Add publisher" %>
      <% end %>
    </div>
  </div>

  <div class="critics_section">
    <h3>Critics (<%= game.critics_count %>)</h3>
    <%= render "critics/form", critic: critic, criticable: game %>
    <% game.critics.each do |critic| %>
      <%= render "critics/critic", critic: critic %>
    <% end %>
  </div>
</div>

app/views/games/_game_card.html.erb
<div class=game_card>
  <div class="game_card-content">
    <% if game.cover.attached? %>
      <%= image_tag game.cover, alt: "game cover" %>
    <% else %>
      <p> No image </p>
    <% end %>
    <h2><%= game.name%></h2>
    <p><span><%= game.release_date ? game.release_date.year : "-" %></span></p>
    <p><span><%= game.rating ? game.rating : "0.0" %></span></p>
    <p><%= game.summary %></p>
  </div>
  <div class="game_card-footer">
    <p><span><%= game.critics_count %> Critics</span></p>
    <%= link_to "Edit", edit_game_path(game) %>
    <%= button_to "Delete", game, method: :delete%>
  </div>
</div>

app/views/games/edit.html.erb
<h1>Edit game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>
<%= link_to "New game", new_game_path %>

<div id="games">
  <% @games.each do |game| %>
    <%= render "game_card", game: game %>
    <p>
      <%= link_to "Show", game %>
    </p>
  <% end %>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game, involved_company_dev: @involved_company_dev, 
                  involved_company_pub: @involved_company_pub, critic: @critic %>

<div>
  <%= link_to "Back", games_path %>
</div>