config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  resources :games do
    resources :involved_companies, only: %i[create destroy]

    post "add_genre", on: :member
    delete "remove_genre", on: :member

    post "add_platform", on: :member
    delete "remove_platform", on: :member

    resources :critics, only: %i[create]
  end
  resources :companies do
    resources :critics, only: %i[create]
  end

  resources :critics, only: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
  # Associations
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies

  has_many :critics, as: :criticable, dependent: :destroy

  has_one_attached :cover

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :description, length: { in: 5..200 }, allow_nil: true
  validates :start_date, comparison: { less_than: Time.zone.now }, allow_nil: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
    @critic = Critic.new
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: "Company was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to companies_path, notice: "Company was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url, notice: "Company was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description, :start_date, :country, :critics_count, :cover)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company_card.html.erb
<div class=company_card>
  <div class="company_card-content">
    <% if company.cover.attached? %>
      <%= image_tag company.cover, alt: "company cover" %>
    <% else %>
     <p> No image </p>
    <% end %>
    <h2><%= company.name%></h2>
    <p><span><%= "#{company.start_date.year} - #{company.country}"%></span></p>
    <p><%= company.description %></p>
  </div>
  <div class="comapny_card-footer">
    <p><span><%= company.games_count %> Games</span></p>
    <%= link_to "Edit", edit_company_path(company) %>
    <%= button_to "Delete", company, method: :delete%>
  </div>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <% if company.cover.attached? %>
      <%= image_tag company.cover %>
    <% end %>
    <%= form.label :cover, style: "display: block" %>
    <%= form.file_field :cover %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back", companies_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Companies</h1>

<%= link_to "New Company", new_company_path %>

<div id="companies">
  <% @companies.each do |company| %>
    <%= render "company_card", company: company %>
    <p>
      <%= link_to "Show", company %>
    </p>
  <% end %>
</div>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back", companies_path %>
</div>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="company_header">
  <% if @company.cover.attached? %>
    <%= image_tag @company.cover, alt: "company_cover" %>
  <% end %>
  <h1><%= @company.name %></h1>
  <p><span><%= "#{@company.start_date.year} - #{@company.country}" %></span></p>
</div>

<div class="company_details">
  <h3>Company Details</h3>
  <p><%= @company.description %></p>
  <h4>Games (<%= @company.games_count%>)</h4>
  <% @company.games.each do |game| %>
    <%= render "games/game_card", game: game %>
  <% end %>
</div>

<div class="company_critics">
  <h3>Critics (<%= @company.critics_count%>)</h3>
  <%= render "critics/form", criticable: @company ,critic: @critic %>
  <% @company.critics.each do |critic| %>
    <%= render "critics/critic", critic: critic %>
  <% end %>
</div>

<div>
  <%= link_to "Back", companies_path %>
</div>